### PR TITLE
[WIP] Connection expiration random delay

### PR DESCRIPTION
**Pull request by hex2a**
This PR adds a configurable random delay (per-connection) to the connection timeout.

most tests are missing, please let me know if you have any input on that.

### CODE REVIEW

**Comment by jeremyevans** [comment]
This looks good, thanks for the patch!  I'm guessing this is to avoid the thundering herd if you are preallocating connections at startup. There are some thread-safety issues in the implementation, and I'll probably change this to storing an array in `@connection_expiration_timestamps` instead of adding another instance variable, but I should be able to merge and test this today.

**Comment by mschfh** [comment]
thank you,
is there a date when this will be released?

**Comment by hex2a** [comment]
thank you,
is there an ETA for a release?

**Comment by jeremyevans** [comment]
Standard Sequel release policy is a new minor version around the first of every month.  So the next release should be around next Tuesday.

**Comment by fertobar** [comment]
great! this new feature will prevent massive expiration and reconnection near same time when we use in high scalability with Puma

**Pull request merged**
