### PR TITLE
migration.rdoc: Added whitespace

### PR DESCRIPTION
**Pull request by perlun**
Just a minor change I thought about while reading the docs. What do you think?

### CODE REVIEW

**Comment by jeremyevans** [comment]
Sequel style is no space between method names and opening block brace if the method doesn't take arguments.  Most (though not all) of the codebase is like that.

**Comment by perlun** [comment]
> Most (though not all) of the codebase is like that.

OK, makes sense to keep the documentation in line with the project's official style. Btw, have you considered making a `.rubocop.yml` file tweaked to follow the "official" Sequel style? Many of us are using Rubocop for our own projects, and our editors are configured to run it automatically etc. Having a project-specific `.rubocop.yml` would make it easier for everyone to follow the suggested style.

However, if you're completely against Rubocop and find it too much of a nitpick, then I will do my best to not try to push this subject any further. 😇

**Comment by jeremyevans** [comment]
I don't think it makes sense to have a `.rubocop.yml` file considering that Sequel development doesn't use rubocop.  It makes sense to have one when the project uses it and enforces the use of it, but that is not the case with Sequel.

**Comment by perlun** [comment]
> I don't think it makes sense to have a .rubocop.yml file considering that Sequel development doesn't use rubocop.

Hehe, that's not quite what I meant. 😄 If we were to add a Rubocop settings file, we should of course use Rubocop to some degree. (and as mentioned, some of us already use it)

If we (= you plus the rest of the community) don't want to use Rubocop, it's a different matter. Is that what you're saying (you feel that it is too picky, too much work to introduce it at this stage, don't see the need, whatever)? Note that I'm not in any way making _demands_ here, merely asking questions. I personally use Rubocop a lot and find it a very useful tool since it helps me write a lot better Ruby code than otherwise.

**Comment by jeremyevans** [comment]
Automated style checkers lead to a focus on how the code looks, as opposed to how it works.  Every development tool added is a barrier to contribution. I don't feel the trade off is worth it.

**Comment by perlun** [comment]
I respect your opinion on this @jeremyevans. I see it quite differently. To me, (enforced) uniformity means that all code will look the same which means we can focus _more_ on how it works instead of get distracted by variety in how it looks. (People are different; I will see how it looks whether I have a tool that reminds me about it or not. Others might not.)

But Sequel is owned by you, so I respect your right to choose in this matter.

**Pull request closed without merging**
