### PR TITLE
"Communication link failure" can also mean disconnect

### PR DESCRIPTION
**Pull request by perlun**
We've had this in our own monkey patches for this class for some time now, but I felt it's better to submit it upstream. :wink:

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for the patch.  This looks good, but can you please combine the two error messages into a single regexp?

**Comment by perlun** [comment]
@jeremyevans Unsure of how to do that, my regex fu is no up to speed I think. 😉 But, I changed it to `#start_with?` instead, which is what Rubocop recommends instead of \A regexps. Could you live with this approach?

**Comment by jeremyevans** [comment]
@perlun `/\A(pattern1|pattern2)/`.  That's what we use in other adapters, and it scales better (think 5+ disconnect error types).

**Comment by perlun** [comment]
Ok, fair points! Thanks for fixing. 👍🏻

**Pull request closed without merging**
