### PR TITLE
Trim all redundant whitespaces

### PR DESCRIPTION
**Pull request by luong-komorebi**
I am sorry if I am being a nitpick kind of person, but I am tinkering a lot with this source code to serve my projects and found that it has a lot of whitespaces here and there, which I think is really unnecessary

### CODE REVIEW

**Comment by luong-komorebi** [comment]
Result of test on Travis: https://travis-ci.org/luong-komorebi/sequel/builds/508232571?utm_source=github_status&utm_medium=notification

**Comment by AlexWayfer** [comment]
Did you read [Pull Request Guidelines](https://github.com/jeremyevans/sequel/blob/0ab96cd/CONTRIBUTING)? The fourth point.

**Comment by jeremyevans** [comment]
As the contribution guidelines state, Sequel is not pedantic about trailing whitespace.  This commit would just make using tools like git blame harder.

**Comment by luong-komorebi** [comment]
Sorry guys, I missed the important point from the PR guideline.

**Pull request closed without merging**
