### PR TITLE
Add a retry_sleep option to Database#transaction

### PR DESCRIPTION
**Pull request by uhoh-itsmaciek**
This allows Sequel to pause between retries which can help with serialization conflicts on slow queries.

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for the patch.  This looks good.  Unfortunately, it's missed the cutoff for 4.19.0, so it will have to wait until 4.20.0.  I'll try merging this on Monday.

I think we may want to remove the `to_i` call, so you can set it to sleep for less than a second.  But I can take care of that after merging.

**Comment by uhoh-itsmaciek** [comment]
No problem re: cutoff. And I agree on dropping the `to_i`.

**Comment by jeremyevans** [comment]
I've given this some more thought, and think a more flexible idea would be a `:before_retry` option that took a proc that would be called with `num_retries` whenever a retry was performed.  You could use this for simple sleeping, for sleeping with exponential backoff, for extra logging, or for anything else.  Thoughts?

**Comment by uhoh-itsmaciek** [comment]
Sure, that makes sense. I added the error that was raised as well--I think as long as we're going general, that can be useful. It's in #941.

**Comment by jeremyevans** [comment]
Closing in favor of #941

**Pull request closed without merging**
