### PR TITLE
Add `plural_association_methods` plugin with `add_*s` and `remove_*s` methods

### PR DESCRIPTION
**Pull request by AlexWayfer**
Helpers for mass adding.

Accept only Arrays for additional arguments and composite keys support.

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for the patch. I don't want to add additional modification methods for every *_to_many association by default.  It bloats the number of methods.  I was strongly considering removing mutation methods by default and only adding them if explicitly specified in Sequel 5, but I finally decided it wasn't worth the backwards compatibility breakage.

While I don't want to do this by default, this is something that could be added by an plugin easily.  Can you refactor this to be a plugin?

**Comment by AlexWayfer** [comment]
> While I don't want to do this by default, this is something that could be added by an plugin easily. Can you refactor this to be a plugin?

I thought about this. OK, I can try.

**Comment by AlexWayfer** [comment]
Done, I guess.

**Comment by jeremyevans** [comment]
Thanks for this.  I will try to review and merge tomorrow.

**Pull request merged**
