### PR TITLE
Support unsigned decimals

### PR DESCRIPTION
**Pull request by akimd**
Hi,

This PR addresses a limitation I hit: one of my columns' type was "decimal(7,2) unsigned", which was not recognized and therefore treated as a string.

Cheers!

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for the report and patch.  Can you refactor your patch to not use the Regexp `x` modifier?

**Comment by akimd** [comment]
Sure.  So you don't think it makes things clearer?

**Comment by jeremyevans** [comment]
I would prefer that we not add it, for consistency with the other regexps.  Also, I don't think it makes things clearer.

**Comment by akimd** [comment]
Jeremy, do you have a release scheduled?  I would need to update that gem (and tapsoob, which depends upon it) in my production deployments.  TIA!

**Comment by flash-gordon** [comment]
@akimd see https://github.com/jeremyevans/sequel#sequel-release-policy- and https://github.com/jeremyevans/sequel/releases I would expect the next release on Oct 1 or so :)

**Comment by akimd** [comment]
> https://github.com/jeremyevans/sequel/releases

Oh yes, I sense there's a pattern in there :-)

**Pull request merged**
