### PR TITLE
Use postgres:latest during CI

### PR DESCRIPTION
**Pull request by kaiquekandykoga**
I think it makes sense to run tests using a newer version of PostgreSQL.

Thank you very much.

### CODE REVIEW

**Review by AlexWayfer — APPROVED** [review]
Maybe we even should have a matrix, but I think this proposition makes better anyway.

**Comment by jeremyevans** [comment]
I tried `postgres:latest` in one of my other libraries a few months ago and it didn't work, but I approved CI for this pull request.  If CI passes, we can merge it.

**Comment by jeremyevans** [comment]
Just FYI, I test Sequel with all versions of PostgreSQL from 8.4 to the latest version before every Sequel release.

**Comment by AlexWayfer** [comment]
> I approved CI for this pull request. If CI passes, we can merge it.

FYI GitHub is having an incident with Actions right now: https://www.githubstatus.com/incidents/fpk08rxnqjz2

**Comment by jeremyevans** [comment]
CI fails with this, with a similar error I've seen before (unrelated to any incident with Actions).  I'm going to close this.  If you can get it working in your fork, please resubmit.

**Comment by AlexWayfer** [comment]
@kaiquekandykoga FYI:

CI fail: https://github.com/jeremyevans/sequel/runs/5572030229?check_suite_focus=true
The first SO answer: https://stackoverflow.com/a/60618750/2630849
Similar PR: https://github.com/jveillet/tentacles-dashboard/pull/207/files

**Pull request closed without merging**
