### PR TITLE
Changing the warn to print

### PR DESCRIPTION
**Pull request by LIQRGV**
warn will having it's output on stderr which is giving error status on ansible task if we execute it

### CODE REVIEW

**Comment by jeremyevans** [comment]
Then redirect stderr to stdout for the task.  Warnings should be printed to stderr, not stdout.  One way to work around this would be do: `def DB.server_version; 80100 end` directly after creating your Database object.

You may want to consider upgrading your PostgreSQL installation, as versions before 8.2 are ancient and long out of support.  

 Also, in the future, as specified in the contribution guidelines, do not include whitespace changes with code changes.

**Comment by LIQRGV** [comment]
Thanks for the input.
FYI, some database like AWS redshift cant updated to latest version.
Sad.

**Comment by jeremyevans** [comment]
If you are using redshift and not PostgreSQL, you may want to use a redshift-specific adapter such as https://github.com/remind101/sequel-redshift

**Comment by LIQRGV** [comment]
Thanks bro!!!
Thats helpfull....

**Pull request closed without merging**
